	/*
	 * ExcuteConstraint.cu
	 * 
	 * ***************   Notice   ***************
	 * Auto Generated By ATPC on:2019-03-07 17:05:30
	 * Author: ZhangHui
	 * 
	 */ 

	#include <iostream>

	#include "./../ConstraintParser/ConstraintParameter.cuh"
	#include "./../model/Coodinate.cuh"
	#include "./../model/Interval.cuh"
	#include "./../model/Priority.cuh"
	#include "./../model/FullCoveredInfo.cuh"
	#include "./../model/PredictValue.cuh"
	#include "./../model/PredictValueWithOne.cuh"
	#include "./../solver/type.h"
	#include "./../solver/ATG.h"
	#include "./../solver/PCATG.h"
	#include "./../solver/ConstantValue.h"
	#include "ExcuteConstraint.cuh"
	#include "HardwareStrategy.cuh"

	#include "ParallelATG.cuh"

	#include "cuda_runtime.h"
	#include "device_launch_parameters.h"
	#include "device_functions.hpp"
	#include "math_functions.h"

	#include <stdio.h>

	using namespace std;

	/*
	 * 这个文件是函数获取运行时刻的各种函数的声明
	 * */ 

	/*
	 * 注意这里计算有两部的计算优化：
	 * 1）在计算运行时刻值的时候，顺便把子约束满足情况计算了
	 * 2）计算子约束的满足情况的时候没有使用if等判断分支结构，
	 *    同时使用到已经计算好的运行时刻值去减少复杂的浮点数计算过程
	 * 这里采用的编码函数命名编码规则是这样的:
	 * getRuntimeValue_i_j表示计算第i个析取范式的第j个约束的运行时刻值
	 * */ 
	/*
	 * 第0个约束的CUDA计算函数
	 * */ 
	__device__ void getRuntimeValue_0_0(FloatType DOUBLE_doubleA , FloatType DOUBLE_doubleB , Coodinate* res )
	{
		res->y = ( DOUBLE_doubleA ) - ( 1.1000000000000001E+0 );
		res->isCovered = (bool)(res->y != 0.f);
		res->isValid = (bool)(isfinite(res->y));
		return ;
	}

	/*
	 * 第1个约束的CUDA计算函数
	 * */ 
	__device__ void getRuntimeValue_0_1(FloatType DOUBLE_doubleA , FloatType DOUBLE_doubleB , Coodinate* res )
	{
		res->y = ( -1.0E+0 ) - ( DOUBLE_doubleB );
		res->isCovered = (bool)(res->y >= 0.f);
		res->isValid = (bool)(isfinite(res->y));
		return ;
	}

	/*
	 * 第2个约束的CUDA计算函数
	 * */ 
	__device__ void getRuntimeValue_0_2(FloatType DOUBLE_doubleA , FloatType DOUBLE_doubleB , Coodinate* res )
	{
		res->y = ( -1.0E+0 ) - ( DOUBLE_doubleA );
		res->isCovered = (bool)(res->y > 0.f);
		res->isValid = (bool)(isfinite(res->y));
		return ;
	}


	/*
	 * 下面是所有的  约束  在  各个搜索方向  的获取运行时刻值的关系（假如n个约束m个搜索方向，那么一共 m*n 个函数）
	 * */ 

	/*
	 * 第0个约束在第0个搜索方向的执行
	 * */ 
	__global__ void calaConstraint_0_0_0(Coodinate* dev_predictArray,FloatType* dev_parameter,const int base,const int Size)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		if (i < Size)
		{
			getRuntimeValue_0_0(dev_predictArray[i+base].x , dev_parameter[1] , dev_predictArray + i + base);
		}
	}

	/*
	 * 第0个约束在第1个搜索方向的执行
	 * */ 
	__global__ void calaConstraint_0_0_1(Coodinate* dev_predictArray,FloatType* dev_parameter,const int base,const int Size)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		if (i < Size)
		{
			getRuntimeValue_0_0(dev_parameter[0] , dev_predictArray[i+base].x , dev_predictArray + i + base);
		}
	}



	/*
	 * 第1个约束在第0个搜索方向的执行
	 * */ 
	__global__ void calaConstraint_0_1_0(Coodinate* dev_predictArray,FloatType* dev_parameter,const int base,const int Size)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		if (i < Size)
		{
			getRuntimeValue_0_1(dev_predictArray[i+base].x , dev_parameter[1] , dev_predictArray + i + base);
		}
	}

	/*
	 * 第1个约束在第1个搜索方向的执行
	 * */ 
	__global__ void calaConstraint_0_1_1(Coodinate* dev_predictArray,FloatType* dev_parameter,const int base,const int Size)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		if (i < Size)
		{
			getRuntimeValue_0_1(dev_parameter[0] , dev_predictArray[i+base].x , dev_predictArray + i + base);
		}
	}



	/*
	 * 第2个约束在第0个搜索方向的执行
	 * */ 
	__global__ void calaConstraint_0_2_0(Coodinate* dev_predictArray,FloatType* dev_parameter,const int base,const int Size)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		if (i < Size)
		{
			getRuntimeValue_0_2(dev_predictArray[i+base].x , dev_parameter[1] , dev_predictArray + i + base);
		}
	}

	/*
	 * 第2个约束在第1个搜索方向的执行
	 * */ 
	__global__ void calaConstraint_0_2_1(Coodinate* dev_predictArray,FloatType* dev_parameter,const int base,const int Size)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		if (i < Size)
		{
			getRuntimeValue_0_2(dev_parameter[0] , dev_predictArray[i+base].x , dev_predictArray + i + base);
		}
	}



	/*
	 * 复合约束的并行计算模块,注意，这个函数还可以使用CUDA提供的流加速计算
	 * */ 
	void calaRuntimeValue(int paraIndex,Coodinate* dev_predictArray,FloatType* dev_parameter,const int row,const int col)
	{
		Block res = HardwareStrategy::getHardwareStrategy(col);

		//根据不同的搜索方向做判断
		if(paraIndex == 0)
		{
			calaConstraint_0_0_0<<<res.NumOfBlock , res.ThreadPreBlock , 0 , ParallelATG::stream[0]>>>(dev_predictArray,dev_parameter,0*col,col);
			calaConstraint_0_1_0<<<res.NumOfBlock , res.ThreadPreBlock , 0 , ParallelATG::stream[1]>>>(dev_predictArray,dev_parameter,1*col,col);
			calaConstraint_0_2_0<<<res.NumOfBlock , res.ThreadPreBlock , 0 , ParallelATG::stream[2]>>>(dev_predictArray,dev_parameter,2*col,col);
		}
		else if(paraIndex == 1)
		{
			calaConstraint_0_0_1<<<res.NumOfBlock , res.ThreadPreBlock , 0 , ParallelATG::stream[0]>>>(dev_predictArray,dev_parameter,0*col,col);
			calaConstraint_0_1_1<<<res.NumOfBlock , res.ThreadPreBlock , 0 , ParallelATG::stream[1]>>>(dev_predictArray,dev_parameter,1*col,col);
			calaConstraint_0_2_1<<<res.NumOfBlock , res.ThreadPreBlock , 0 , ParallelATG::stream[2]>>>(dev_predictArray,dev_parameter,2*col,col);
		}
		else
		{
			cout<<"************   You Should Never Get Here. In Function Of: void calaRuntimeValue(int paraIndex,Coodinate* dev_predictArray,FloatType* dev_parameter,const int row,const int col)"<<endl;
		}

		//下面是流并行计算部分的同步
		ParallelATG::synStream();
	}


	/*
	 *  这个核函数是为了寻找可行解
	 * */ 
	__global__ void calaFeasibleSolution(FullCoveredInfo* dev_coveredInfo,Coodinate* dev_predictArray,const int Size)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		if (i < Size)
		{
			dev_coveredInfo[i].index = i;
			dev_coveredInfo[i].isCovered = dev_predictArray[i + 0*Size].isCovered && dev_predictArray[i + 1*Size].isCovered && dev_predictArray[i + 2*Size].isCovered;
			dev_coveredInfo[i].isVaild =  dev_predictArray[i + 0*Size].isValid && dev_predictArray[i + 1*Size].isValid && dev_predictArray[i + 2*Size].isValid;
			dev_coveredInfo[i].vaildNum = (int)(dev_coveredInfo[i].isVaild == true);
		}
	}

	/*
	 * 就是区间交运算的计算
	 * */ 
	__global__ void calaFinalIntervel(Interval* dev_finalIntervel,Interval* dev_interval,const int calaArraySize)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		bool condition = (i>=1) && (i<calaArraySize);
		if(condition)
		{
			Interval* a0 = dev_interval + i + calaArraySize * 0;
			Interval* a1 = dev_interval + i + calaArraySize * 1;
			Interval* a2 = dev_interval + i + calaArraySize * 2;

			FloatType left = a0->left;
			left = fmaxf( left , a1->left);
			left = fmaxf( left , a2->left);

			FloatType right = a0->right;
			right = fminf( right , a1->right);
			right = fminf( right , a2->right);

			bool hasIntervel = a0->hasIntervel && a1->hasIntervel && a2->hasIntervel;
			dev_finalIntervel[i].left = left;
			dev_finalIntervel[i].right = right;
			dev_finalIntervel[i].hasIntervel = hasIntervel;
			//这里可以自行添加打印获取区间交运算的结果
			//printf("(%f , %f ) (%f , %f ) (%f , %f ) Final %d (%f , %f)\n",a1->left,a1->right,a2->left,a2->right,a3->left,a3->right,hasIntervel,left,right);
		}
	}

	/*
	 * 根据预测的序列生成predct矩阵
	 * */ 
	__global__ void generatePredictMat(Coodinate* dev_predictArray,PredictValueWithOne* dev_finalAllPredictValue,const int Size)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		if( i < Size )
		{
			dev_predictArray[i + 0*Size].x = dev_finalAllPredictValue[i].value;
			dev_predictArray[i + 1*Size].x = dev_finalAllPredictValue[i].value;
			dev_predictArray[i + 2*Size].x = dev_finalAllPredictValue[i].value;
		}
	}

	/*
	 * 并行计算所有的预测解向量的优先级
	 * */ 
	__global__ void calaPriority(Priority* dev_priority,Coodinate* dev_calaArray,const int row,const int Size)
	{
		int i = threadIdx.x + blockIdx.x*blockDim.x;
		if( i < Size )
		{
			FloatType pri = 0.0;
			Coodinate* a0 = dev_calaArray + i + 0 * Size;

			Coodinate* a1 = dev_calaArray + i + 1 * Size;

			Coodinate* a2 = dev_calaArray + i + 2 * Size;

			if(a0->isCovered==true) pri = pri + 1.f;
			else if(a0->isValid==true) pri = pri + 1.f/(1.f+fabsf(a0->y));

			if(a1->isCovered==true) pri = pri + 1.f;
			else if(a1->isValid==true) pri = pri + 1.f/(1.f+fabsf(a1->y));

			if(a2->isCovered==true) pri = pri + 1.f;
			else if(a2->isValid==true) pri = pri + 1.f/(1.f+fabsf(a2->y));

			dev_priority[i].priority =  pri / (FloatType)row;
			dev_priority[i].x = a0->x;

			//下面是测试代码
			bool isOne = (a0->x == a1->x) && (a1->x == a2->x);
			bool isCovered = a0->isCovered && a1->isCovered && a2->isCovered;
			bool isValid= a0->isValid && a1->isValid && a2->isValid;
			if(isCovered == true)
			{
				printf("Cala Prioruty Wrong,index:%d: (%f,%f,%d,%d) , (%f,%f,%d,%d) , (%f,%f,%d,%d) , isOne:%d , isCovered:%d , isValid:%d  \n",i,a0->x,a0->y,a0->isCovered,a0->isValid,a1->x,a1->y,a1->isCovered,a1->isValid,a2->x,a2->y,a2->isCovered,a2->isValid,isOne,isCovered,isValid);
			}
		}
	}

