	/*
	 * ConstraintParameter.cu
	 * 
	 * ***************   Notice   ***************
	 * Auto Generated By ATPC on:2019-03-07 17:05:30
	 * Author: ZhangHui
	 * 
	 */ 

	#include <iostream>

	#include <vector>

	#include <map>

	#include "./../solver/type.h"
	#include "./../solver/ConstantValue.h"
	#include "./../model/RuntimeValue.h"
	#include "ConstraintParameter.cuh"

	using namespace std;


	/*
	 * 约束的名字信息
	 * */ 
	string ConstraintParameter::constraintName = "PLFFSolver";

	/*
	 * 约束的变量类型，使用bool变量表示，1表示浮点数，0表示整形
	 * */ 
	bool ConstraintParameter::constraintVarType[NUM_OF_PARAM] = { 1 , 1 };

	/*
	 * 变量的名字信息
	 * */ 
	string ConstraintParameter::constraintVarName[NUM_OF_PARAM] = { "DOUBLE_doubleA" , "DOUBLE_doubleB" };

	/*
	 * 变量的整体依赖关系，使用bool变量表示，1表示相关，0表示不相关
	 * */ 
	bool ConstraintParameter::constraintDependencyRela[NUM_OF_PARAM] = { true , true };

	/*
	 * 所有的约束的比较运算符的类型信息
	 * 1 表示> , >= , < , <=四种情况
	 * 0 表示 == 情况
	 * -1 表示 ！= 情况
	 * */ 
	int ConstraintParameter::constraintCompType[Num_Of_Constraints] =  { -1 , 1 , 1 };

	/*
	 * 这个参数是用来记录当存在不可行解的时候，为什么不存在解的原因
	 * */ 
	string ConstraintParameter::noSolutionInfo = "";

	/*
	 * 所有的求解的结果的保留,这个主要存储的是经过化简求解过的变量的对应的值
	 * */ 
	map<string, FloatType> ConstraintParameter::allVarEqualMap;

	/*
	 * 所有的求解的结果的保留,这个主要存储的是每一个变量的定义域，
	 * */ 
	FloatType ConstraintParameter::left[NUM_OF_PARAM] = {-1.0E10 , -1.0E10};

	FloatType ConstraintParameter::right[NUM_OF_PARAM] = {1.0E10 , 1.0E10};

	/*
	 * 这个函数主要是针对复合约束预处理后的结果的初始化函数，由于是C++98的标准，没有办法直接初始化
	 * 主要有allVarEqualMap
	 * */ 
	void ConstraintParameter::initConstraintPreprocess()
	{
	}

	/*
	 * 这个函数是用来获取约束的信息
	 * */ 
	vector< vector<string> > ConstraintParameter::getConstraintInfo()
	{
		vector< vector<string> > res;

		vector<string> HeQv1;
		HeQv1.push_back("DOUBLE_doubleA!=1.1000000000000001E+0");
		HeQv1.push_back("-1.0E+0>=DOUBLE_doubleB");
		HeQv1.push_back("-1.0E+0>DOUBLE_doubleA");

		res.push_back(HeQv1);

		return res;
	}

	/*
	 * 这个函数是用来获取约束的运行时刻值，用于CPU验证
	 * */ 
	vector< vector<RuntimeValue*> > ConstraintParameter::getCoveredInfo(FloatType* nums)
	{
		vector< vector<RuntimeValue*> > res;

		vector<RuntimeValue*> HeQv1;

		RuntimeValue* tmp_0_0 = getConstraintValue_0_0(nums[0] , nums[1]);
		HeQv1.push_back(tmp_0_0);
		RuntimeValue* tmp_0_1 = getConstraintValue_0_1(nums[0] , nums[1]);
		HeQv1.push_back(tmp_0_1);
		RuntimeValue* tmp_0_2 = getConstraintValue_0_2(nums[0] , nums[1]);
		HeQv1.push_back(tmp_0_2);

		res.push_back(HeQv1);

		return res;
	}

	/*
	 * 下面是最后在CPU对求出的可行解向量做验证的函数，
	 * 主要就是计算每一个简单子约束的运行时刻值，以及每一个简单自约束的满足情况
	 * */ 
	RuntimeValue* ConstraintParameter::getConstraintValue_0_0( FloatType DOUBLE_doubleA , FloatType DOUBLE_doubleB )
	{
		FloatType value = ( DOUBLE_doubleA ) - ( 1.1000000000000001E+0 );
		bool isCovered = (bool)(value != 0.f);
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_1( FloatType DOUBLE_doubleA , FloatType DOUBLE_doubleB )
	{
		FloatType value = ( -1.0E+0 ) - ( DOUBLE_doubleB );
		bool isCovered = (bool)(value >= 0.f);
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

	RuntimeValue* ConstraintParameter::getConstraintValue_0_2( FloatType DOUBLE_doubleA , FloatType DOUBLE_doubleB )
	{
		FloatType value = ( -1.0E+0 ) - ( DOUBLE_doubleA );
		bool isCovered = (bool)(value > 0.f);
		RuntimeValue* one = new RuntimeValue(value,isCovered);
		return one;
	}

